import { useEffect, useState, useCallback } from 'react'
import {
  Loader2, RefreshCw, ChevronDown, ChevronUp,
  Copy, Check, Save, Play, Search, Plus, X, RotateCcw,
  AlertTriangle, Zap, CheckCircle, AlertCircle, Hash, MessageSquare, Sparkles, Trash2, Wand2
} from 'lucide-react'
import { supabase } from '../lib/supabase'

type Script = {
  id: string; show_id: string; series_topic: string; series_part: number | null
  series_week_start: string | null; part_title: string; script_text: string
  caption: string; status: string; post_date: string | null; post_time_utc: string
}
type ShowInfo = { id: string; show_name: string; display_name: string; color: string }
type SocialContent = { script_id: string; hook: string; caption: string; cta: string; hashtags: string[]; status: string }

const STATUS_COLOR: Record<string, string> = {
  draft:      'bg-nova-border/50 text-nova-muted',
  ready:      'bg-nova-gold/20 text-nova-gold',
  processing: 'bg-nova-violet/20 text-nova-violet',
  done:       'bg-green-400/20 text-green-400',
  failed:     'bg-nova-crimson/20 text-nova-crimson',
  scripting:  'bg-blue-400/20 text-blue-400',
}

const SHOW_COLORS: Record<string, string> = {
  sunday_power_hour: '#C9A84C',
  motivation_court:  '#2A9D8F',
  tea_time_with_cj:  '#9B5DE5',
  confession_court:  '#C1121F',
}

const DAY = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
const PART_LABEL = ['Opening','Part 1','Part 2','Part 3','Part 4','Part 5','Part 6']
const EMPTY_FORM = {
  show_id: '', series_topic: '', series_part: '0',
  part_title: '', script_text: '', caption: '',
  post_date: '', post_time_utc: '13:00', status: 'draft'
}

export default function Scripts() {
  const [scripts, setScripts]   = useState<Script[]>([])
  const [shows, setShows]       = useState<ShowInfo[]>([])
  const [loading, setLoading]   = useState(true)
  const [search, setSearch]     = useState('')
  const [showFilter, setShowFilter] = useState('all')
  const [statusFilter, setStatusFilter] = useState('all')
  const [expanded, setExpanded] = useState<Record<string, boolean>>({})
  const [edits, setEdits]       = useState<Record<string, Script>>({})
  const [saving, setSaving]     = useState<string | null>(null)
  const [copied, setCopied]     = useState<string | null>(null)
  const [producing, setProducing] = useState<string | null>(null)
  const [produceMsg, setProduceMsg] = useState<Record<string, string>>({})
  const [socialMap, setSocialMap]     = useState<Record<string, SocialContent>>({})
  const [copiedField, setCopiedField] = useState<string | null>(null)
  const [confirmDelete, setConfirmDelete] = useState<string | null>(null)
  const [deleting, setDeleting]           = useState<string | null>(null)
  const [showCreate, setShowCreate] = useState(false)
  const [creating, setCreating]     = useState(false)
  const [form, setForm]             = useState({ ...EMPTY_FORM })
  const [createError, setCreateError] = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    const [{ data: sc }, { data: sh }] = await Promise.all([
      supabase.from('show_scripts')
        .select('id,show_id,series_topic,series_part,series_week_start,part_title,script_text,caption,status,post_date,post_time_utc')
        .order('post_date', { ascending: true }).order('series_part', { ascending: true }),
      supabase.from('show_configs').select('id,show_name,display_name,color').order('display_name'),
    ])
    const scripts = sc ?? []
    setScripts(scripts as Script[])
    setShows(sh ?? [])
    // Load social content for all scripts
    if (scripts.length > 0) {
      const ids = scripts.map((s: Script) => s.id)
      const { data: socialRows } = await supabase
        .from('nova_social_content')
        .select('script_id,hook,caption,cta,hashtags,status')
        .in('script_id', ids)
      if (socialRows) {
        const map: Record<string, SocialContent> = {}
        ;(socialRows as SocialContent[]).forEach(r => { if (r.script_id) map[r.script_id] = r })
        setSocialMap(map)
      }
    }
    setLoading(false)
  }, [])

  useEffect(() => { load() }, [load])

  // Auto-poll every 4s while any script is being generated by NOVA
  useEffect(() => {
    const anyScripting = scripts.some(s => s.status === 'scripting')
    if (!anyScripting) return
    const t = setInterval(load, 4000)
    return () => clearInterval(t)
  }, [scripts, load])

  const save = async (id: string) => {
    const patch = edits[id]
    if (!patch) return
    setSaving(id)
    // Optimistic update — show scripting spinner immediately before DB round-trip
    if (patch.status === 'scripting') {
      setScripts(prev => prev.map(s => s.id === id ? { ...s, status: 'scripting' } : s))
    }
    await supabase.from('show_scripts').update(patch).eq('id', id)
    setEdits(prev => { const n = { ...prev }; delete n[id]; return n })
    setSaving(null)
    load()
  }

  const copyField = (text: string, key: string) => {
    navigator.clipboard.writeText(text)
    setCopiedField(key)
    setTimeout(() => setCopiedField(null), 2000)
  }

  const deleteScript = async (id: string) => {
    setDeleting(id)
    setConfirmDelete(null)
    // CASCADE FK auto-deletes nova_social_content row
    await supabase.from('show_scripts').delete().eq('id', id)
    setScripts(prev => prev.filter(s => s.id !== id))
    setSocialMap(prev => { const n = { ...prev }; delete n[id]; return n })
    setEdits(prev => { const n = { ...prev }; delete n[id]; return n })
    setExpanded(prev => { const n = { ...prev }; delete n[id]; return n })
    setDeleting(null)
  }

  // Produce with NOVA: set script status to 'ready' — triggers DB trigger -> ai-show-producer
  const produceWithNova = async (script: Script) => {
    const show = shows.find(s => s.id === script.show_id)
    if (!show?.show_name) {
      setProduceMsg(p => ({ ...p, [script.id]: 'Show config not found' }))
      return
    }
    if (script.status === 'processing' || script.status === 'ready') {
      setProduceMsg(p => ({ ...p, [script.id]: 'Already queued or producing' }))
      return
    }
    setProducing(script.id)
    setProduceMsg(p => ({ ...p, [script.id]: '' }))
    try {
      const { error } = await supabase.from('show_scripts').update({ status: 'ready' }).eq('id', script.id)
      if (error) throw error
      setProduceMsg(p => ({ ...p, [script.id]: 'Queued for NOVA production' }))
      load()
    } catch (e) {
      setProduceMsg(p => ({ ...p, [script.id]: `Error: ${String(e)}` }))
    }
    setProducing(null)
  }

  const createScript = async () => {
    if (!form.show_id || !form.script_text.trim()) { setCreateError('Show and script text required'); return }
    setCreating(true); setCreateError('')
    try {
      const { error } = await supabase.from('show_scripts').insert({
        show_id: form.show_id,
        series_topic: form.series_topic,
        series_part: parseInt(form.series_part) || 0,
        part_title: form.part_title,
        script_text: form.script_text,
        caption: form.caption,
        post_date: form.post_date || null,
        post_time_utc: form.post_time_utc,
        status: form.status,
      })
      if (error) throw error
      setShowCreate(false)
      setForm({ ...EMPTY_FORM })
      load()
    } catch (e) { setCreateError(String(e)) }
    setCreating(false)
  }

  const showForScript = (s: Script) => shows.find(sh => sh.id === s.show_id)

  const filtered = scripts.filter(s => {
    const sh = showForScript(s)
    const matchShow = showFilter === 'all' || sh?.show_name === showFilter
    const matchStatus = statusFilter === 'all' || s.status === statusFilter
    const matchSearch = !search || [s.series_topic, s.part_title, s.script_text, s.caption]
      .some(f => f?.toLowerCase().includes(search.toLowerCase()))
    return matchShow && matchStatus && matchSearch
  })

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="font-display text-3xl text-white tracking-wide">Scripts</h1>
          <p className="text-xs font-mono text-nova-muted mt-0.5">{scripts.length} total</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => setShowCreate(v => !v)}
            className="flex items-center gap-2 px-3 py-2 rounded-xl bg-nova-gold text-nova-navy text-sm font-body hover:brightness-110 transition-all">
            <Plus size={14} /> Create Script
          </button>
          <button onClick={load} className="nova-btn-ghost p-2 text-xs">
            <RefreshCw size={13} />
          </button>
        </div>
      </div>

      {/* Create form */}
      {showCreate && (
        <div className="nova-card border border-nova-gold/30 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="font-display text-nova-gold">New Script</h3>
            <button onClick={() => setShowCreate(false)} className="text-nova-muted hover:text-white">
              <X size={16} />
            </button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-mono text-nova-muted mb-1">Show *</label>
              <select value={form.show_id} onChange={e => setForm(f => ({...f, show_id: e.target.value}))} className="nova-input w-full">
                <option value="">Select show...</option>
                {shows.map(s => <option key={s.id} value={s.id}>{s.display_name}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-xs font-mono text-nova-muted mb-1">Part Title</label>
              <input value={form.part_title} onChange={e => setForm(f => ({...f, part_title: e.target.value}))}
                className="nova-input w-full" placeholder="Episode or Part title" />
            </div>
            <div className="md:col-span-2">
              <label className="block text-xs font-mono text-nova-muted mb-1">Series Topic</label>
              <input value={form.series_topic} onChange={e => setForm(f => ({...f, series_topic: e.target.value}))}
                className="nova-input w-full" placeholder="Overarching series topic" />
            </div>
            <div className="md:col-span-2">
              <label className="block text-xs font-mono text-nova-muted mb-1">Script Text *</label>
              <textarea value={form.script_text} onChange={e => setForm(f => ({...f, script_text: e.target.value}))}
                className="nova-input w-full h-32 resize-none" placeholder="Full script text..." />
            </div>
            <div className="md:col-span-2">
              <label className="block text-xs font-mono text-nova-muted mb-1">Caption</label>
              <textarea value={form.caption} onChange={e => setForm(f => ({...f, caption: e.target.value}))}
                className="nova-input w-full h-16 resize-none" placeholder="Social media caption..." />
            </div>
            <div>
              <label className="block text-xs font-mono text-nova-muted mb-1">Post Date</label>
              <input type="date" value={form.post_date} onChange={e => setForm(f => ({...f, post_date: e.target.value}))} className="nova-input w-full" />
            </div>
            <div>
              <label className="block text-xs font-mono text-nova-muted mb-1">Status</label>
              <select value={form.status} onChange={e => setForm(f => ({...f, status: e.target.value}))} className="nova-input w-full">
                <option value="draft">Draft</option>
                <option value="ready">Ready (queues for NOVA production)</option>
              </select>
            </div>
          </div>
          {createError && <p className="text-nova-crimson text-xs font-mono">{createError}</p>}
          <div className="flex items-center gap-2">
            <button onClick={createScript} disabled={creating}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-nova-gold text-nova-navy text-sm font-body hover:brightness-110 disabled:opacity-50 transition-all">
              {creating ? <><Loader2 size={13} className="animate-spin" /> Creating...</> : <><Plus size={13} /> Create Script</>}
            </button>
            <button onClick={() => { setShowCreate(false); setForm({ ...EMPTY_FORM }) }} className="nova-btn-ghost text-sm">Cancel</button>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-40">
          <Search size={12} className="absolute left-3 top-1/2 -translate-y-1/2 text-nova-muted" />
          <input value={search} onChange={e => setSearch(e.target.value)}
            className="nova-input pl-8 text-xs w-full" placeholder="Search scripts..." />
        </div>
        <select value={showFilter} onChange={e => setShowFilter(e.target.value)} className="nova-input text-xs">
          <option value="all">All Shows</option>
          {shows.map(s => <option key={s.id} value={s.show_name}>{s.display_name}</option>)}
        </select>
        <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="nova-input text-xs">
          <option value="all">All Status</option>
          {['draft','scripting','ready','processing','done','failed'].map(s => <option key={s} value={s}>{s === 'scripting' ? '⚡ scripting' : s}</option>)}
        </select>
      </div>

      {loading ? (
        <div className="flex justify-center py-20"><Loader2 size={24} className="animate-spin text-nova-gold" /></div>
      ) : filtered.length === 0 ? (
        <div className="nova-card text-center py-16">
          <p className="font-display text-nova-muted text-2xl tracking-wide">NO SCRIPTS</p>
          <p className="text-sm font-body text-nova-muted mt-2">Create a script above to get started.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map(script => {
            const sh = showForScript(script)
            const color = sh ? (SHOW_COLORS[sh.show_name] ?? '#C9A84C') : '#C9A84C'
            const isExpanded = expanded[script.id]
            const edit = edits[script.id] ?? script
            const isDirty = Boolean(edits[script.id])
            const canProduce = ['draft','failed'].includes(script.status) && Boolean(sh)
            const isProducing = producing === script.id
            const canDelete   = ['draft','failed','scripting'].includes(script.status)
            const isScripting = script.status === 'scripting'
            const isDeleting  = deleting  === script.id
            const confirming  = confirmDelete === script.id

            return (
              <div key={script.id} className="nova-card">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap mb-1">
                      {sh && (
                        <span className="text-xs font-mono px-2 py-0.5 rounded-full"
                          style={{ backgroundColor: `${color}18`, color }}>
                          {sh.display_name}
                        </span>
                      )}
                      <span className={`nova-badge ${STATUS_COLOR[script.status] ?? 'bg-nova-border text-nova-muted'}`}>
                        {script.status}
                      </span>
                      {script.series_part !== null && (
                        <span className="text-[10px] font-mono text-nova-muted">
                          {PART_LABEL[script.series_part] ?? `Part ${script.series_part}`}
                        </span>
                      )}
                    </div>
                    <p className="text-sm font-body text-white font-semibold">
                      {script.part_title || script.series_topic || 'Untitled Script'}
                    </p>
                    {script.series_topic && script.part_title && (
                      <p className="text-xs font-mono text-nova-muted mt-0.5">{script.series_topic}</p>
                    )}
                    {script.post_date && (
                      <p className="text-xs font-mono text-nova-muted mt-0.5">
                        {DAY[new Date(script.post_date + 'T00:00:00').getDay()]} {script.post_date} @ {script.post_time_utc} UTC
                      </p>
                    )}
                    {/* Social content preview */}
                    {socialMap[script.id]?.hook && (
                      <div className="mt-2 space-y-1.5">
                        <p className="text-xs text-nova-muted leading-relaxed italic border-l-2 pl-2"
                          style={{ borderColor: color }}>
                          &#8220;{socialMap[script.id].hook}&#8221;
                        </p>
                        {socialMap[script.id].hashtags?.length > 0 && (
                          <div className="flex flex-wrap gap-1 mt-1">
                            {socialMap[script.id].hashtags.slice(0,6).map(h => (
                              <span key={h} className="text-[10px] font-mono px-1.5 py-0.5 rounded"
                                style={{ background: `${color}15`, color: color }}>
                                #{h}
                              </span>
                            ))}
                            {socialMap[script.id].hashtags.length > 6 && (
                              <span className="text-[10px] font-mono text-nova-muted">
                                +{socialMap[script.id].hashtags.length - 6}
                              </span>
                            )}
                          </div>
                        )}
                      </div>
                    )}
                    {/* Scripting indicator — NOVA is writing */}
                    {isScripting && (
                      <div className="mt-2 flex items-center gap-2 text-xs font-mono rounded-lg px-3 py-2 border border-blue-400/25" style={{ background: 'rgba(96,165,250,0.06)' }}>
                        <Loader2 size={11} className="animate-spin flex-shrink-0 text-blue-400" />
                        <span className="text-blue-300">NOVA is writing this script — status will flip to <strong>ready</strong> automatically.</span>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-1.5 flex-shrink-0 flex-wrap justify-end">
                    {/* Produce button — only when draft/failed and not currently scripting */}
                    {canProduce && !isScripting && (
                      <button onClick={() => produceWithNova(script)} disabled={isProducing}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-mono text-white transition-all disabled:opacity-50"
                        style={{ background: 'linear-gradient(135deg, #9B5DE5, #2A9D8F)' }}>
                        {isProducing
                          ? <><Loader2 size={11} className="animate-spin" /> Queuing...</>
                          : <><Zap size={11} /> Produce</>}
                      </button>
                    )}
                    {/* Scripting: NOVA is generating the script via Claude */}
                    {isScripting && (
                      <span className="flex items-center gap-1.5 text-xs font-mono text-blue-400">
                        <Wand2 size={11} className="animate-pulse" /> Writing...
                      </span>
                    )}
                    {script.status === 'processing' && (
                      <span className="flex items-center gap-1 text-xs font-mono text-nova-violet">
                        <Loader2 size={11} className="animate-spin" /> Producing
                      </span>
                    )}
                    {script.status === 'done' && <CheckCircle size={14} className="text-green-400" />}
                    {script.status === 'failed' && !isScripting && (
                      <button onClick={() => produceWithNova(script)} disabled={isProducing}
                        className="flex items-center gap-1 text-xs font-mono text-nova-crimson hover:text-nova-gold transition-colors">
                        <RotateCcw size={11} /> Retry
                      </button>
                    )}
                    {/* Expand/collapse */}
                    <button onClick={() => setExpanded(p => ({...p, [script.id]: !p[script.id]}))}
                      className="nova-btn-ghost p-1.5">
                      {isExpanded ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
                    </button>
                    {/* Delete button — inline confirm, only for draft/failed/scripting */}
                    {canDelete && !confirming && !isDeleting && (
                      <button onClick={() => setConfirmDelete(script.id)}
                        className="nova-btn-ghost p-1.5 hover:text-nova-crimson transition-colors"
                        title="Delete script">
                        <Trash2 size={13} />
                      </button>
                    )}
                    {confirming && (
                      <span className="flex items-center gap-1.5">
                        <span className="text-xs font-mono text-nova-crimson">Delete?</span>
                        <button onClick={() => deleteScript(script.id)}
                          className="text-xs font-mono px-2 py-0.5 rounded bg-nova-crimson/20 text-nova-crimson hover:bg-nova-crimson/30 transition-colors">
                          Yes
                        </button>
                        <button onClick={() => setConfirmDelete(null)}
                          className="text-xs font-mono px-2 py-0.5 rounded bg-nova-border text-nova-muted hover:text-white transition-colors">
                          No
                        </button>
                      </span>
                    )}
                    {isDeleting && (
                      <span className="flex items-center gap-1 text-xs font-mono text-nova-crimson">
                        <Loader2 size={11} className="animate-spin" /> Deleting...
                      </span>
                    )}
                  </div>
                </div>

                {/* Produce message */}
                {produceMsg[script.id] && (
                  <p className={`text-xs font-mono mt-2 ${
                    produceMsg[script.id].startsWith('Error')
                      ? 'text-nova-crimson' : 'text-nova-teal'
                  }`}>
                    {produceMsg[script.id]}
                  </p>
                )}

                {/* Expanded editor */}
                {isExpanded && (
                  <div className="mt-4 space-y-3 border-t border-nova-border pt-4">
                    <div>
                      <label className="block text-xs font-mono text-nova-muted mb-1">Part Title</label>
                      <input value={edit.part_title ?? ''}
                        onChange={e => setEdits(p => ({...p, [script.id]: {...(p[script.id] ?? script), part_title: e.target.value}}))}
                        className="nova-input w-full text-xs" />
                    </div>
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-xs font-mono text-nova-muted">Script Text</label>
                        <button onClick={() => { navigator.clipboard.writeText(script.script_text); setCopied(script.id) }}
                          className="text-nova-muted hover:text-nova-gold p-0.5 transition-colors">
                          {copied === script.id ? <Check size={12} className="text-nova-teal" /> : <Copy size={12} />}
                        </button>
                      </div>
                      <textarea value={edit.script_text ?? ''}
                        onChange={e => setEdits(p => ({...p, [script.id]: {...(p[script.id] ?? script), script_text: e.target.value}}))}
                        className="nova-input w-full h-40 resize-none text-xs" />
                    </div>
                    <div>
                      <label className="block text-xs font-mono text-nova-muted mb-1">Caption</label>
                      <textarea value={edit.caption ?? ''}
                        onChange={e => setEdits(p => ({...p, [script.id]: {...(p[script.id] ?? script), caption: e.target.value}}))}
                        className="nova-input w-full h-20 resize-none text-xs" />
                    </div>
                    {/* Social Content Section */}
                    {socialMap[script.id] && (
                      <div className="space-y-3 p-3 rounded-xl border border-nova-border/50" style={{ background: `${color}08` }}>
                        <p className="text-xs font-mono uppercase tracking-widest flex items-center gap-1.5" style={{ color }}>
                          <Sparkles size={10} /> Social Content
                        </p>
                        {/* Hook */}
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <label className="text-[10px] font-mono text-nova-muted uppercase tracking-widest">Hook</label>
                            <button onClick={() => copyField(socialMap[script.id].hook, script.id+'-hook')}
                              className="text-nova-muted hover:text-nova-gold transition-colors p-0.5">
                              {copiedField === script.id+'-hook' ? <Check size={11} className="text-nova-teal" /> : <Copy size={11} />}
                            </button>
                          </div>
                          <p className="text-xs text-white leading-relaxed italic">"{socialMap[script.id].hook}"</p>
                        </div>
                        {/* Caption */}
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <label className="text-[10px] font-mono text-nova-muted uppercase tracking-widest">Caption</label>
                            <button onClick={() => copyField(socialMap[script.id].caption, script.id+'-cap')}
                              className="text-nova-muted hover:text-nova-gold transition-colors p-0.5">
                              {copiedField === script.id+'-cap' ? <Check size={11} className="text-nova-teal" /> : <Copy size={11} />}
                            </button>
                          </div>
                          <p className="text-xs text-nova-muted leading-relaxed">{socialMap[script.id].caption}</p>
                        </div>
                        {/* CTA */}
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <label className="text-[10px] font-mono text-nova-muted uppercase tracking-widest flex items-center gap-1"><MessageSquare size={9} /> Comment CTA</label>
                            <button onClick={() => copyField(socialMap[script.id].cta, script.id+'-cta')}
                              className="text-nova-muted hover:text-nova-gold transition-colors p-0.5">
                              {copiedField === script.id+'-cta' ? <Check size={11} className="text-nova-teal" /> : <Copy size={11} />}
                            </button>
                          </div>
                          <p className="text-xs text-white font-medium">{socialMap[script.id].cta}</p>
                        </div>
                        {/* Hashtags */}
                        <div>
                          <div className="flex items-center justify-between mb-1">
                            <label className="text-[10px] font-mono text-nova-muted uppercase tracking-widest flex items-center gap-1"><Hash size={9} /> Hashtags</label>
                            <button onClick={() => copyField(socialMap[script.id].hashtags.map(h=>'#'+h).join(' '), script.id+'-ht')}
                              className="text-nova-muted hover:text-nova-gold transition-colors p-0.5">
                              {copiedField === script.id+'-ht' ? <Check size={11} className="text-nova-teal" /> : <Copy size={11} />}
                            </button>
                          </div>
                          <div className="flex flex-wrap gap-1">
                            {socialMap[script.id].hashtags.map(h => (
                              <span key={h} className="text-[10px] font-mono px-1.5 py-0.5 rounded"
                                style={{ background: `${color}18`, color }}>#{h}</span>
                            ))}
                          </div>
                        </div>
                        {/* Copy All */}
                        <button onClick={() => {
                          const sc = socialMap[script.id]
                          const full = [sc.hook, sc.caption, sc.cta, sc.hashtags.map(h=>'#'+h).join(' ')].filter(Boolean).join('\n\n')
                          copyField(full, script.id+'-all')
                        }} className="flex items-center gap-1.5 text-xs font-mono px-3 py-1.5 rounded-lg transition-all w-full justify-center"
                          style={{ background: `${color}18`, color }}>
                          {copiedField === script.id+'-all' ? <><Check size={11} /> Copied!</> : <><Copy size={11} /> Copy Full Post</>}
                        </button>
                      </div>
                    )}
                    <div className="flex items-center gap-2 flex-wrap">
                      <div>
                        <label className="block text-xs font-mono text-nova-muted mb-1">Status</label>
                        <select value={edit.status}
                          onChange={e => setEdits(p => ({...p, [script.id]: {...(p[script.id] ?? script), status: e.target.value}}))}
                          className="nova-input text-xs">
                          {['draft','ready','processing','done','failed','scripting'].map(s =>
                            <option key={s} value={s}>{s === 'scripting' ? '⚡ Generate Script (NOVA)' : s}</option>)}
                        </select>
                      </div>
                      <div>
                        <label className="block text-xs font-mono text-nova-muted mb-1">Post Date</label>
                        <input type="date" value={edit.post_date ?? ''}
                          onChange={e => setEdits(p => ({...p, [script.id]: {...(p[script.id] ?? script), post_date: e.target.value}}))}
                          className="nova-input text-xs" />
                      </div>
                    </div>
                    {isDirty && (
                      <button onClick={() => save(script.id)} disabled={saving === script.id}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-nova-gold text-nova-navy text-xs font-mono hover:brightness-110 disabled:opacity-50 transition-all">
                        {saving === script.id
                          ? <><Loader2 size={11} className="animate-spin" /> Saving...</>
                          : <><Save size={11} /> Save Changes</>}
                      </button>
                    )}
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
